<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8usg9oc\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8usg9oc/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8usg9oc.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8usg9oc\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8usg9oc\appProdProjectContainer([
    'container.build_hash' => '8usg9oc',
    'container.build_id' => 'd0d65617',
    'container.build_time' => 1598422377,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8usg9oc');
