<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerE7rjzac\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerE7rjzac/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerE7rjzac.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerE7rjzac\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerE7rjzac\appProdProjectContainer([
    'container.build_hash' => 'E7rjzac',
    'container.build_id' => 'd8ce89d9',
    'container.build_time' => 1597213045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerE7rjzac');
